### ISSUE TITLE
segfault on garbage collector

### ISSUE THREAD

**Issue by davidonet** [oaubert/python-vlc#2] opened 2015-02-04 08:50 UTC
I'm building a software for on stage performance and I use vlc pyhton binding to play 2 synchronised videos and switch from a media to an other with a websocket interface. 

https://github.com/davidonet/cas1soft/tree/master/server

I use callback to methods to get position and mediaend reached 
I got segfault on media change after a few minute

    Program received signal SIGSEGV, Segmentation fault.
    0x0000003fc9a05cd1 in ffi_closure_unix64_inner () from /usr/lib64/libffi.so.5

I've investigated the problem and found this info : https://github.com/JohannesBuchner/PyMultiNest/issues/5

So I tried a case that "segfault" all the time 
    
    player.pause()
    gc.collect()
    player.pause()

leads to segfault in libvlc

The workaround I found is to 

* deactivate automatic garbage collector
* call `gc.collect()` after `player.stop()` and before `player.set_media(...)`

https://github.com/davidonet/cas1soft/blob/master/server/cas1server.py#L88

**Comment by oaubert** [comment] 2015-02-04 10:34
Thanks for the precise report. It is strange since the EventManager.event_attach method (that you appropriately use) was wrapped to avoid precisely this (garbage collecting of callbacks) - it adds an indirection layer with a generic callback method (stored as an EventManager instance variable, so it should not be dereferenced) and stores callbacks in its own dictionary, so they should not be dereferenced either. 

I wrote a simple script to try to reproduce your issue, but it did not crash. Could you have a look and see if you can modify it to exhibit the issue ? It is in the gcbug branch:
https://github.com/oaubert/python-vlc/blob/gcbug/tests/gctest.py

**Comment by oaubert** [comment] 2015-02-04 15:58
Looks like there are 2 distinct issues :

- the gctest.py code exhibits a problem when quickly updating event handlers. On my computer, it freezes but does not crash. I guess we may observe the same behaviour with native libvlc, it looks like some concurrent access issue.

- your code has another issue: you regularly change the self.vlc_events. Hence, when switching, the reference to the old EventManager (python wrapper) is lost, and the reference to the callbacks it held is lost too, generating a segmentation fault. The native libvlc_mediaplayer_event_manager method always return the same address (there is only 1 event_manager instance per object), but different python wrappers will be generated each time, which is a bug that I just fixed in 0e1f6637de106b0608346c64fdf7394b6fdb0199 
But anyway, once it is fixed, you should still be having the 1st issue mentioned above (and on top of that, you _attach multiple times events but do not _detach them)

I would recommend against changing too often the callbacks. Instead, I would _attach the event handlers for both players once at initialization, and add a test at the beginning of the callback to determine if the event comes from the "reference" player or not before processing the event.

**Closed by oaubert** 2015-02-04 15:58 UTC

**Comment by davidonet** [comment] 2015-02-04 16:33
Thanx for all the info.
I'll change my event manager strategy according to your advice.
