### ISSUE TITLE
Media get_meta(vlc.Meta.Description) No Longer Returns Description

### ISSUE THREAD

**Issue by vlcfriend** [oaubert/python-vlc#143] opened 2020-07-03 19:23 UTC
Media object get_meta(vlc.Meta.Description) method no longer returns description for meta data with python-vlc 3.0.10114 and VLC version 3.0.11.   In VLC Media player (3.0.11) itself, the comment field in Audio Media Information option now returns nothing as well.   The phenomenon occurs when accessing network streams (i.e., URLs).

**Comment by oaubert** [comment] 2020-07-12 20:43
It works OK with local files (I just added a test to check it). Could you provide a network stream URL exhibiting the issue so that this issue can be tested/reproduced?

**Comment by vlcfriend** [comment] 2020-07-12 21:25
Hi –

 

Below are some YouTube URLs that exhibit the phenomenon where the description is no longer returned with Media get_meta(vlc.Meta.Description) using the latest versions of VLC and python-vlc.    

 

https://www.youtube.com/watch?v=kdKltNx42AQ  (Space Shuttle)

https://www.youtube.com/watch?v=gTVoFCP1BLg   (E.T. Bicycle over moon)

**Comment by oaubert** [comment] 2020-07-12 21:38
This is a libvlc issue, not a python one, so you would have better luck by reporting it to forum.videolan.org.  From a quick investigation, the https://code.videolan.org/videolan/vlc/-/blob/master/share/lua/playlist/youtube.lua LUA script tries to fetch the description, but the parsing is very fragile (using a regexp on some element) and the corresponding line has not been updated since 2016. Youtube changed a lot since then, so the lua file should be updated to reflect these changes. I am closing this issue in the python-vlc bindings (since it is not python specific), but feel free to add references to related conversations to it.

**Closed by oaubert** 2020-07-12 21:38 UTC
